export type TFont = "black" | "bold" | "medium" | "regular" | "light" | "thin";

export enum FONT {
  RobotoBlack = "RobotoBlack",
  RobotoBold = "RobotoBold",
  RobotoMedium = "RobotoMedium",
  RobotoRegular = "RobotoRegular",
  RobotoLight = "RobotoLight",
  RobotoThin = "RobotoThin",
}

export const FONTS = {
  RobotoBlack: require("../assets/fonts/Roboto-Black.ttf"),
  RobotoBold: require("../assets/fonts/Roboto-Bold.ttf"),
  RobotoMedium: require("../assets/fonts/Roboto-Medium.ttf"),
  RobotoRegular: require("../assets/fonts/Roboto-Regular.ttf"),
  RobotoLight: require("../assets/fonts/Roboto-Light.ttf"),
  RobotoThin: require("../assets/fonts/Roboto-Thin.ttf"),
};

// https://hexcolorpedia.com/color/?q=db1a5a
export const COLOR = {
  white: "#eee",
  black: "#111",
  primary: "#db1a5a",
  secondary: "#131313",
  accent: "#19db9a",
  surface: "#1c1c21",
  border: "",
  text: "",
  muted: "",
  button: "",
  hover: "",
  disabled: "",
  //
  light: {
    primary: "#2C638B",
    surfaceTint: "#2C638B",
    onPrimary: "#FFFFFF",
    primaryContainer: "#CCE5FF",
    onPrimaryContainer: "#001D31",
    secondary: "#51606F",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#D4E4F6",
    onSecondaryContainer: "#0D1D2A",
    tertiary: "#8F4C34",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#FFDBCF",
    onTertiaryContainer: "#380D00",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    background: "#F7F9FF",
    onBackground: "#181C20",
    surface: "#F7F9FF",
    onSurface: "#181C20",
    surfaceVariant: "#DEE3EB",
    onSurfaceVariant: "#42474E",
    outline: "#72787E",
    outlineVariant: "#C2C7CE",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2D3135",
    inverseOnSurface: "#EEF1F6",
    inversePrimary: "#99CCFA",
    primaryFixed: "#CCE5FF",
    onPrimaryFixed: "#001D31",
    primaryFixedDim: "#99CCFA",
    onPrimaryFixedVariant: "#074B72",
    secondaryFixed: "#D4E4F6",
    onSecondaryFixed: "#0D1D2A",
    secondaryFixedDim: "#B8C8DA",
    onSecondaryFixedVariant: "#394857",
    tertiaryFixed: "#FFDBCF",
    onTertiaryFixed: "#380D00",
    tertiaryFixedDim: "#FFB59B",
    onTertiaryFixedVariant: "#72351F",
    surfaceDim: "#D7DADF",
    surfaceBright: "#F7F9FF",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F1F4F9",
    surfaceContainer: "#EBEEF3",
    surfaceContainerHigh: "#E6E8EE",
    surfaceContainerHighest: "#E0E2E8",
  },
  dark: {
    primary: "#99CCFA",
    surfaceTint: "#99CCFA",
    onPrimary: "#003351",
    primaryContainer: "#074B72",
    onPrimaryContainer: "#CCE5FF",
    secondary: "#B8C8DA",
    onSecondary: "#23323F",
    secondaryContainer: "#394857",
    onSecondaryContainer: "#D4E4F6",
    tertiary: "#FFB59B",
    onTertiary: "#55200B",
    tertiaryContainer: "#72351F",
    onTertiaryContainer: "#FFDBCF",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    background: "#101418",
    onBackground: "#E0E2E8",
    surface: "#101418",
    onSurface: "#E0E2E8",
    surfaceVariant: "#42474E",
    onSurfaceVariant: "#C2C7CE",
    outline: "#8C9198",
    outlineVariant: "#42474E",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#E0E2E8",
    inverseOnSurface: "#2D3135",
    inversePrimary: "#2C638B",
    primaryFixed: "#CCE5FF",
    onPrimaryFixed: "#001D31",
    primaryFixedDim: "#99CCFA",
    onPrimaryFixedVariant: "#074B72",
    secondaryFixed: "#D4E4F6",
    onSecondaryFixed: "#0D1D2A",
    secondaryFixedDim: "#B8C8DA",
    onSecondaryFixedVariant: "#394857",
    tertiaryFixed: "#FFDBCF",
    onTertiaryFixed: "#380D00",
    tertiaryFixedDim: "#FFB59B",
    onTertiaryFixedVariant: "#72351F",
    surfaceDim: "#101418",
    surfaceBright: "#36393E",
    surfaceContainerLowest: "#0B0F12",
    surfaceContainerLow: "#181C20",
    surfaceContainer: "#1C2024",
    surfaceContainerHigh: "#272A2E",
    surfaceContainerHighest: "#313539",
  },
};
