import { StyleSheet } from "react-native";
import { FONT } from "@/constants/THEME";

export const typographyStyles = StyleSheet.create({
  displayLarge: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 57,
    letterSpacing: -0.25,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 45,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 36,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLargeBold: {
    fontFamily: FONT.RobotoBold,
    fontWeight: "700",
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineLarge: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 16,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  bodyLarge: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 12,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  labelLargeBold: {
    fontFamily: FONT.RobotoBold,
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMediumBold: {
    fontFamily: FONT.RobotoBold,
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelMedium: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 11,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
});
